import Header from "./Header";
import Footer from "./Footer";
import Head from "next/head";

function Layout({ children }) {
  return (
    <>
      <Head>
        <title>
          Polkadot: Web3 Interoperability | Decentralized Blockchain
        </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main>{children}</main>
      <Footer />
    </>
  );
}
export default Layout;
